import test from "node:test";
import assert from "node:assert/strict";
import { generateFoundryHarness } from "../dist/harness.js";

test("generates an isolated Foundry review scaffold", () => {
  const finding = { id: "static:test:Example.sol:10", programId: "unknown", title: "Candidate", category: "access-control", severity: "high", confidence: 0.9, evidence: ["Example.sol:10"], status: "new", createdAt: new Date().toISOString() };
  const h = generateFoundryHarness(finding);
  assert.match(h.path, /test\/onchain-hunter\//);
  assert.match(h.content, /AUTO-GENERATED BY ONCHAIN-HUNTER/);
  assert.match(h.content, /TODO: implement/);
});
