import type { Opportunity } from "./types.js";

export type Harness = { path: string; content: string; findingId: string; };
function safe(s: string): string { return s.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 80); }

export function generateFoundryHarness(finding: Opportunity, contractName = "Target"): Harness {
  const name = safe(finding.id);
  const content = [
    "// AUTO-GENERATED BY ONCHAIN-HUNTER",
    "// This harness is intentionally a review scaffold. It does not send transactions to live networks.",
    "pragma solidity ^0.8.20;",
    "",
    'import "forge-std/Test.sol";',
    "",
    "contract " + name + "Test is Test {",
    "    address internal target;",
    "",
    "    function setUp() public {",
    "        // TODO: deploy the authorized source code or attach to a local fork.",
    "        // target = address(new " + contractName + "());",
    "    }",
    "",
    "    function test_candidate_" + safe(finding.category) + "() public {",
    "        // Candidate: " + finding.title.replace(/\n/g, " "),
    "        // Finding ID: " + finding.id,
    "        // Expected evidence: " + (finding.evidence[0] ?? "").replace(/\n/g, " "),
    '        fail("TODO: implement a minimal local reproduction for this candidate.");',
    "    }",
    "}"
  ].join("\n") + "\n";
  return { path: "test/onchain-hunter/" + name + ".t.sol", content, findingId: finding.id };
}
